# Generated by Django 3.0.7 on 2021-09-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210926_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
